catalog:
  glue:
    type: glue
    s3.endpoint: s3.us-east-1.amazonaws.com
    warehouse: s3://52fcde3e7-5582-477d-7686ou4ij1ptxj8equ83a5xc51fsuse1b--table-s3  # Test
    # warehouse: 154735606025  # OE
    region: us-east-1
    glue_region: us-east-1
  sql:
    type: sql
    # location for pre-existing local catalog. Don't use this location when using the API's catalog caching feature
    uri: sqlite://///tmp/icefabric_local_catalog/pyiceberg_catalog.db
    warehouse: file:///tmp/icefabric_local_catalog/warehouse
    # For a glue catalog that will be cached use:
    # uri: sqlite:////tmp/warehouse/pyiceberg_catalog.db
    # warehouse: file:///tmp/warehouse

# icefabric runtime configuration
icefabric:
  # Set to false to skip refreshing SQL from Glue on startup.
  # Useful when the local, cached catalog is already populated.
  build_cache: true
