from .hydrofabric_update import (
    NHD,
    Divides,
    Flowpaths,
    Gages,
    Hydrolocations,
    Lakes,
    LakesPolygons,
    LakeVFPCrosswalk,
    Nexus,
    ReferenceFlowpaths,
    ReservoirDA,
    VirtualFlowpaths,
    VirtualNexus,
)

nhf_layers = {
    "divides": Divides,
    "flowpaths": Flowpaths,
    "nexus": Nexus,
    "reference_flowpaths": ReferenceFlowpaths,
    "gages": Gages,
    "virtual_flowpaths": VirtualFlowpaths,
    "virtual_nexus": VirtualNexus,
    "hydrolocations": Hydrolocations,
    "lakes": Lakes,
    "nhd": NHD,
    "lakes_polygons": LakesPolygons,
    "reservoir_da": ReservoirDA,
    "lake_vfp_crosswalk": LakeVFPCrosswalk,
}
