services:
  nginx:
    image: nginx:latest
    container_name: icefabric-nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - dashboard
  api:
    image: icefabric/api
    container_name: icefabric-api
    build:
      context: ../
      dockerfile: docker/Dockerfile.api
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - ICEFABRIC_DEPLOY_ENV=${ICEFABRIC_DEPLOY_ENV:-test}
    env_file:
      - ../${ICEFABRIC_CREDS_ENV_FILE}
  dashboard:
    image: icefabric/dashboard
    container_name: icefabric-dashboard
    build:
      context: ../
      dockerfile: docker/Dockerfile.streamlit
    ports:
      - "127.0.0.1:8501:8501"
    environment:
      - ICEFABRIC_DEPLOY_ENV=${ICEFABRIC_DEPLOY_ENV:-test}
    env_file:
      - ../${ICEFABRIC_CREDS_ENV_FILE}
